import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, MessageCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from './utils/supabase'
import './App.css'
import './front-page.css'

type Slide = { id: string; eyebrow: string; title: string; accent: string; description: string; image_url: string; cta_label: string; cta_url: string; caption: string }
const fallback: Slide = { id: 'fallback', eyebrow: 'ARSHAB SURGICAL / EST. IN SIALKOT', title: 'Precision for', accent: 'every procedure.', description: 'Surgical instruments engineered for control, consistency, and the confidence to focus on what matters most.', image_url: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=85', cta_label: 'Explore products', cta_url: '/products', caption: 'Trusted by professionals' }

export default function FrontPage() {
  const [slides, setSlides] = useState<Slide[]>([]); const [active, setActive] = useState(0)
  useEffect(() => { void (async () => { const { data } = await supabase.from('hero_slides').select('id, eyebrow, title, accent, description, image_url, cta_label, cta_url, caption').eq('is_active', true).order('sort_order').order('created_at'); if (data?.length) setSlides(data as Slide[]) })() }, [])
  const items = slides.length ? slides : [fallback]; const slide = items[active] ?? items[0]
  useEffect(() => { if (items.length < 2) return; const timer = window.setInterval(() => setActive(index => (index + 1) % items.length), 6000); return () => window.clearInterval(timer) }, [items.length])
  return <><header className="site-header"><div className="topline"><span>Sialkot, Pakistan</span><span>Precision instruments for confident care</span><a href="mailto:hello@arshabsurgical.com">hello@arshabsurgical.com <ArrowUpRight size={13} /></a></div><nav className="nav wrap"><Link to="/" className="brand"><img className="brand-logo" src="/logo.png" alt="ArShab Surgicals" /></Link><div className="nav-links"><Link to="/about">About</Link><Link to="/products">Products</Link><Link to="/categories">Categories</Link><Link to="/quality">Quality</Link><Link to="/contact">Contact</Link></div><Link className="quote-button" to="/contact">Request a quote <ArrowUpRight size={16} /></Link></nav></header><main><section className="hero wrap"><div className="hero-copy"><p className="eyebrow reveal">{slide.eyebrow}</p><h1 className="reveal delay-1">{slide.title}<br /><i>{slide.accent}</i></h1><p className="hero-lead reveal delay-2">{slide.description}</p><div className="hero-actions reveal delay-3"><Link className="button dark" to={slide.cta_url || '/products'}>{slide.cta_label || 'Explore products'} <ArrowUpRight size={17} /></Link><Link className="button outline" to="/contact">Talk to our team <MessageCircle size={17} /></Link></div><div className="hero-proof reveal delay-3"><span><Check size={15} /> Built for precision</span><span><Check size={15} /> Quality-led sourcing</span></div></div><div className="hero-visual"><div className="hero-orbit"></div><img key={slide.id} src={slide.image_url} alt={slide.caption || slide.title} /><div className="hero-caption"><span className="caption-dot"></span><span>{slide.caption || 'Trusted by professionals'}<br /><strong>across every detail</strong></span></div>{items.length > 1 && <div className="hero-slider-controls"><button onClick={() => setActive(index => (index - 1 + items.length) % items.length)} aria-label="Previous slide"><ChevronLeft size={16} /></button><span>{String(active + 1).padStart(2, '0')} / {String(items.length).padStart(2, '0')}</span><button onClick={() => setActive(index => (index + 1) % items.length)} aria-label="Next slide"><ChevronRight size={16} /></button></div>}</div></section><section className="intro wrap"><div><p className="eyebrow">01 / ABOUT ARSHAB</p><h2>Made with discipline.<br /><i>Delivered with care.</i></h2></div><div className="intro-text"><p>From our home in Sialkot, we supply dependable surgical and medical instruments to professionals, healthcare organizations, and distributors around the world.</p><Link className="text-link" to="/about">Our approach <ArrowUpRight size={15} /></Link></div></section></main></>
}
